name = "WebSearcher"
uuid = "1c63772d-d4c7-4709-8c98-c5fb5b9dfed4"
version = "0.1.0"
authors = ["am3lue <am3lue@gmail.com>"]

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
Flux = "0.16.5"
HTTP = "1.10.19"
JSON = "1.3.0"
